# Generated by Django 3.1.7 on 2021-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('user_image', models.CharField(max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
