# Generated by Django 3.1.7 on 2021-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_paytypes'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_place',
            field=models.ManyToManyField(related_name='place_users', through='order.Order', to='order.Address'),
        ),
    ]
