# Generated by Django 3.1.7 on 2021-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(through='product.ProductSize', to='product.Size'),
        ),
    ]
