# Generated by Django 3.1.7 on 2021-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('mypage', '0001_initial'),
        ('product', '0002_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='questioners',
            field=models.ManyToManyField(through='mypage.Question', to='account.User'),
        ),
    ]
