# Generated by Django 3.1.7 on 2021-03-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
        ('account', '0001_initial'),
        ('product', '0004_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order_product',
            new_name='order_products',
        ),
        migrations.AddField(
            model_name='product',
            name='follwers',
            field=models.ManyToManyField(related_name='product_follow', through='mypage.Favorite', to='account.User'),
        ),
    ]
