# Generated by Django 3.1.7 on 2021-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20210318_1217'),
        ('order', '0002_order_order_paytypes'),
        ('account', '0002_user_order_place'),
        ('product', '0005_auto_20210318_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_products',
        ),
        migrations.AddField(
            model_name='product',
            name='product_orders',
            field=models.ManyToManyField(related_name='ordered_products', through='order.Cart', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='follwers',
            field=models.ManyToManyField(related_name='followed_product', through='mypage.Favorite', to='account.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='questioners',
            field=models.ManyToManyField(related_name='questioned_products', through='mypage.Question', to='account.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='size_products', through='product.ProductSize', to='product.Size'),
        ),
    ]
