# Generated by Django 3.1.7 on 2021-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20210320_1529'),
        ('account', '0003_auto_20210320_1529'),
        ('product', '0006_auto_20210318_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.AddField(
            model_name='product',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewed_products', through='mypage.Review', to='account.User'),
        ),
    ]
