# Generated by Django 3.1.7 on 2021-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_order_place'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrecommand',
            old_name='reivew',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='recommander',
            field=models.ManyToManyField(related_name='recommanded_user', through='mypage.ReviewRecommand', to='account.User'),
        ),
    ]
