# Generated by Django 3.1.7 on 2021-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='seller',
            field=models.CharField(default='seller', max_length=20),
        ),
    ]
