<<<<<<< HEAD:order/migrations/0002_auto_20210324_0459.py
# Generated by Django 3.1.7 on 2021-03-24 04:59
=======
# Generated by Django 3.1.7 on 2021-03-24 02:43
>>>>>>> main:order/migrations/0002_auto_20210324_0243.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:order/migrations/0002_auto_20210324_0459.py
        ('product', '0001_initial'),
        ('account', '0001_initial'),
        ('order', '0001_initial'),
=======
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('account', '0001_initial'),
>>>>>>> main:order/migrations/0002_auto_20210324_0243.py
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
