# Generated by Django 3.1.7 on 2021-03-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_paytypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_order',
        ),
    ]
